// Usage (from extract-pdf/):
//   npx tsx scripts/serve-pdfs.ts
//
// Serves local-data/extract-pdf/pdfs/<quarter>/ over http://localhost:PORT/<quarter>/... so
// the PDF links in every quarter's verify.html (generated by
// generate-verify-html.ts) reliably open in a browser when clicked, each
// against its own quarter's PDF. file:// links don't consistently hand off
// to the OS's default app from every browser, but a plain http:// link
// always does. Leave this running, then click links in verify.html.

import http from "http";
import fs from "fs";
import path from "path";

import { PDF_SERVER_PORT } from "./constants";

const ROOT_DIR = path.join(__dirname, "..");
const PDFS_ROOT_DIR = path.join(
  ROOT_DIR,
  "..",
  "..",
  "local-data",
  "extract-pdf",
  "pdfs",
);

const server = http.createServer((req, res) => {
  const requestedPath = decodeURIComponent((req.url || "/").split("?")[0]);
  const filePath = path.join(PDFS_ROOT_DIR, requestedPath);

  // Prevent serving anything outside PDFS_ROOT_DIR.
  if (!filePath.startsWith(PDFS_ROOT_DIR)) {
    res.writeHead(403);
    res.end("Forbidden");
    return;
  }

  fs.stat(filePath, (err, stats) => {
    if (err || !stats.isFile()) {
      res.writeHead(404);
      res.end("Not found");
      return;
    }
    res.writeHead(200, { "Content-Type": "application/pdf" });
    fs.createReadStream(filePath).pipe(res);
  });
});

server.listen(PDF_SERVER_PORT, () => {
  console.log(`Serving ${PDFS_ROOT_DIR}`);
  console.log(
    `  -> http://localhost:${PDF_SERVER_PORT}/<quarter>/<symbol>.pdf`,
  );
  console.log("Leave this running, then click PDF links in verify.html.");
  console.log("Press Ctrl+C to stop.");
});
